Repository boostcamp-2020/IssueTracker-06, pull requests merged in 2020-11, with the labels that each got.

#58 Eb/ issue 목록 조회 API 구현
  server/src/api/routes/index.ts
  server/src/api/routes/issues/controller/getIssues.ts
  server/src/api/routes/issues/controller/index.ts
  server/src/api/routes/issues/index.ts
  server/src/service/issue/getIssues.ts
  server/src/service/issue/index.ts
Labels: api, enhancement

#63 Ej/이슈 편집화면 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListEditViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/AssigneeStackView.swift
  iOS/IssueTracker/IssueTracker/View/AssigneeView.swift
  iOS/IssueTracker/IssueTracker/View/BottomDetailView.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewHeader.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/IssueStateView.swift
Labels: enhancement

#64 Th/ 필터 선택 화면
  .gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/taehee.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/IssueTracker/IssueTracker/Controller/FilterSelectTableViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/FilterSelectViewController.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
Labels: enhancement

#95 delete 메소드 구현
  iOS/IssueTracker/IssueTracker/Model/HTTPData.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/VO/User.swift
Labels: enhancement

#94 Ej/ios api
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPData.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/HttpTest.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/Label.swift
  iOS/IssueTracker/IssueTracker/Model/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/MockupData.swift
  iOS/IssueTracker/IssueTracker/Model/User.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/VO/User.swift
Labels: enhancement

#98 Eb/자주쓰이는 atom component 구현 및 molecule component 일부 구현
  client/src/components/atoms/DatePicker/DatePicker.stories.tsx
  client/src/components/atoms/DatePicker/DatePicker.tsx
  client/src/components/atoms/DatePicker/index.ts
  client/src/components/atoms/FilterButton/FilterButton.stories.tsx
  client/src/components/atoms/FilterButton/FilterButton.tsx
  client/src/components/atoms/FilterButton/index.ts
  client/src/components/atoms/InputLabel/InputLabel.stories.tsx
  client/src/components/atoms/InputLabel/InputLabel.tsx
  client/src/components/atoms/InputLabel/index.ts
  client/src/components/atoms/LabelTag/LabelTag.stories.tsx
  client/src/components/atoms/LabelTag/LabelTag.tsx
  client/src/components/atoms/LabelTag/index.ts
  client/src/components/atoms/TextArea/TextArea.stories.tsx
  client/src/components/atoms/TextArea/TextArea.tsx
  client/src/components/atoms/TextArea/index.ts
  client/src/components/atoms/filterItem/ColorSwatch/ColorSwatch.tsx
  client/src/components/atoms/filterItem/ColorSwatch/index.ts
  client/src/components/atoms/filterItem/Description/Description.tsx
  client/src/components/atoms/filterItem/Description/index.ts
  client/src/components/atoms/filterItem/Title/Title.tsx
  client/src/components/atoms/filterItem/Title/index.ts
  client/src/components/molecules/filterItem/FilterItemLabel/FilterItemLabel.stories.tsx
  client/src/components/molecules/filterItem/FilterItemLabel/FilterItemLabel.tsx
  client/src/components/molecules/filterItem/FilterItemLabel/index.ts
  client/src/themes/index.ts
Labels: enhancement, view

#96 Cy/IconText, Button 컴포넌트 구현
  client/.eslintignore
  client/src/components/atoms/Button/Button.stories.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/styleMapper.ts
  client/src/components/atoms/icons/IconTag.tsx
  client/src/components/molecules/TextWithIcon/TextWithIcon.stories.tsx
  client/src/components/molecules/TextWithIcon/TextWithIcon.tsx
  client/src/components/molecules/TextWithIcon/index.ts
  client/src/themes/index.ts
Labels: enhancement, view

#97 Jy/XButton, Input, Search Filter 구현
  client/src/components/atoms/Input/FilterInput.stories.tsx
  client/src/components/atoms/Input/FilterInput.tsx
  client/src/components/atoms/Input/Input.stories.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Input/index.ts
  client/src/components/atoms/icons/Dropdown.tsx
  client/src/components/atoms/icons/Reset.tsx
  client/src/components/atoms/icons/index.ts
  client/src/components/molecules/FilterModal/FilterModal.stories.tsx
  client/src/components/molecules/FilterModal/FilterModal.tsx
  client/src/components/molecules/FilterModal/index.ts
  client/src/components/molecules/XButton/XButton.stories.tsx
  client/src/components/molecules/XButton/XButton.tsx
  client/src/components/molecules/XButton/index.ts
  client/src/components/organisms/SearchFilter/SearchFilter.stories.tsx
  client/src/components/organisms/SearchFilter/SearchFilter.tsx
  client/src/components/organisms/SearchFilter/index.ts
  client/src/themes/index.ts
Labels: enhancement, view

#100 Jy/ refactoring 및 empty message 구현
  client/src/components/atoms/Input/FilterInput.stories.tsx
  client/src/components/atoms/Input/FilterInput.tsx
  client/src/components/atoms/Input/Input.stories.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Input/index.ts
  client/src/components/atoms/filterItem/ColorSwatch/ColorSwatch.tsx
  client/src/components/atoms/filterItem/Description/Description.tsx
  client/src/components/atoms/filterItem/Title/Title.tsx
  client/src/components/atoms/icons/Warning.tsx
  client/src/components/atoms/icons/index.ts
  client/src/components/molecules/EmptyMessage/EmptyMessage.stories.tsx
  client/src/components/molecules/EmptyMessage/EmptyMessage.tsx
  client/src/components/molecules/EmptyMessage/index.ts
  client/src/components/molecules/FilterModal/FilterModal.stories.tsx
  client/src/components/molecules/FilterModal/FilterModal.tsx
  client/src/components/molecules/FilterModal/FilterModalButton/FilterModalButton.stories.tsx
  client/src/components/molecules/FilterModal/FilterModalButton/FilterModalButton.tsx
  client/src/components/molecules/FilterModal/FilterModalButton/filterItem/FilterItemLabel/FilterItemLabel.stories.tsx
  client/src/components/molecules/FilterModal/FilterModalButton/filterItem/FilterItemLabel/FilterItemLabel.tsx
  client/src/components/molecules/FilterModal/FilterModalButton/filterItem/FilterItemLabel/index.ts
  client/src/components/molecules/FilterModal/FilterModalButton/index.ts
  client/src/components/organisms/SearchFilter/SearchFilter.stories.tsx
  client/src/components/organisms/SearchFilter/SearchFilter.tsx
Labels: enhancement, view

#99 Cy/Text, Toggle, Progress Bar 컴포넌트 구현
  client/src/components/atoms/BoldText/BoldText.stories.tsx
  client/src/components/atoms/BoldText/BoldText.tsx
  client/src/components/atoms/BoldText/index.ts
  client/src/components/atoms/Button/Button.stories.tsx
  client/src/components/atoms/icons/IconMilestone.tsx
  client/src/components/atoms/icons/IconSearch.tsx
  client/src/components/molecules/LabelMilestoneToggle/LabelMilestoneToggle.stories.tsx
  client/src/components/molecules/LabelMilestoneToggle/LabelMilestoneToggle.tsx
  client/src/components/molecules/LabelMilestoneToggle/index.ts
  client/src/components/molecules/ProgressBar/ProgressBar.stories.tsx
  client/src/components/molecules/ProgressBar/ProgressBar.tsx
  client/src/components/molecules/ProgressBar/index.ts
  client/src/components/molecules/Search/Search.stories.tsx
  client/src/components/molecules/Search/Search.tsx
  client/src/components/molecules/Search/index.ts
  client/src/components/molecules/TextWithIcon/TextWithIcon.tsx
  client/src/themes/index.ts
Labels: enhancement, view

#107 Milestone 화면 기능 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListEditViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssueDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPData.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/HttpTest.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueListDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/Label.swift
  iOS/IssueTracker/IssueTracker/Model/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/MilestoneDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/MockupData.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/VO/User.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/BottomDetailView.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewHeader.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.xib
Labels: enhancement

#103 Feature/label 목록 화면 구현
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Model/LabelListDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/LabelCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/LabelView.swift
Labels: enhancement

#108 [feat] MilestoneListViewController 연결, 코드컨벤션 맞추기
  iOS/IssueTracker/IssueTracker/Controller/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.xib
Labels: enhancement

#111 Develop/iOS 2주차 코드프리징
  .gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/taehee.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/IssueTracker/IssueTracker/Controller/FilterSelectTableViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/FilterSelectViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListEditViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/Model/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssueDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPData.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/HttpTest.swift
  iOS/IssueTracker/IssueTracker/Model/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/IssueListDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/Label.swift
  iOS/IssueTracker/IssueTracker/Model/LabelListDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/MilestoneDataProvider.swift
  iOS/IssueTracker/IssueTracker/Model/MockupData.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/VO/User.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/AssigneeStackView.swift
  iOS/IssueTracker/IssueTracker/View/AssigneeView.swift
  iOS/IssueTracker/IssueTracker/View/BottomDetailView.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueDetailCollectionViewHeader.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/IssueStateView.swift
  iOS/IssueTracker/IssueTracker/View/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/LabelCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/LabelView.swift
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.xib
Labels: enhancement

#114 Eb/issue list 관련 컴포넌트 구현
  client/src/components/atoms/DatePickerInput/DatePickerInput.tsx
  client/src/components/atoms/LabelTag/LabelTag.tsx
  client/src/components/atoms/TextArea/TextArea.tsx
  client/src/components/atoms/icons/IssueClosed.tsx
  client/src/components/atoms/icons/IssueOpened.tsx
  client/src/components/atoms/icons/icons.stories.tsx
  client/src/components/atoms/icons/index.ts
  client/src/components/atoms/selectMenuItem/Image/Image.stories.tsx
  client/src/components/atoms/selectMenuItem/Image/Image.tsx
  client/src/components/atoms/selectMenuItem/Image/index.ts
  client/src/components/molecules/Assignees/Assignees.stories.tsx
  client/src/components/molecules/Assignees/Assignees.tsx
  client/src/components/molecules/Assignees/index.ts
  client/src/components/molecules/IssueInfo/IssueInfo.stories.tsx
  client/src/components/molecules/IssueInfo/IssueInfo.tsx
  client/src/components/molecules/IssueInfo/index.ts
  client/src/components/organisms/IssueCard/IssueCard.stories.tsx
  client/src/components/organisms/IssueCard/IssueCard.tsx
  client/src/components/organisms/IssueCard/index.ts
  client/src/themes/index.ts
Labels: enhancement, view

#116 Eb/ Issue Info type 오류 수정
  client/src/components/atoms/LabelTag/LabelTag.stories.tsx
  client/src/components/atoms/LabelTag/LabelTag.tsx
  client/src/components/atoms/LabelTag/index.ts
  client/src/components/molecules/IssueInfo/IssueInfo.tsx
Labels: bug

#119 Feature/label,milestone add view
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/Issue/FilterSelectTableViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/FilterSelectViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListEditViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Label/LabelAddViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Label/LabelAddViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Milestone/MilestoneAddViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Milestone/MilestoneAddViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Controller/Milestone/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssueDataManager.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPData.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/IssueListDataManager.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Comment.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issues.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Label.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Labels.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestone.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Milestones.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/AddView/AddView.swift
  iOS/IssueTracker/IssueTracker/View/AddView/AddView.xib
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueDetailCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueDetailCollectionViewHeader.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/LabelCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/LabelCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/MilestoneListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/MilestoneListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/Component/AssigneeStackView.swift
  iOS/IssueTracker/IssueTracker/View/Component/AssigneeView.swift
  iOS/IssueTracker/IssueTracker/View/Component/IssueStateView.swift
  iOS/IssueTracker/IssueTracker/View/Component/LabelView.swift
  iOS/IssueTracker/IssueTracker/View/Component/LabelsStackView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/ColorInputView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/ColorInputView.xib
  iOS/IssueTracker/IssueTracker/View/InputView/ContentInputView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/TextFieldInputView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/TextFieldInputView.xib
  iOS/IssueTracker/IssueTracker/View/InputView/TextViewInputView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/TextViewInputView.xib
  iOS/IssueTracker/IssueTracker/View/MilestoneListCollectionViewCell.swift
Labels: enhancement

#124 Feature/issue edit refactoring
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListCellMode.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListCollectionViewSetting.swift
  iOS/IssueTracker/IssueTracker/Controller/Issue/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Model/HTTPServiceHelper.swift
  iOS/IssueTracker/IssueTracker/Model/IssueListDataManager.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Issues.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueListCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueListCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/InputView/ColorInputView.xib
Labels: enhancement, optional, refactor

#122 Cy/이슈 목록 페이지 구현
  client/src/apis/createIssue.ts
  client/src/apis/getIssues.ts
  client/src/components/molecules/Assignees/Assignees.stories.tsx
  client/src/components/molecules/Assignees/Assignees.tsx
  client/src/components/molecules/Assignees/index.ts
  client/src/components/molecules/IssueInfo/IssueInfo.stories.tsx
  client/src/components/molecules/IssueInfo/IssueInfo.tsx
  client/src/components/molecules/LabelMilestoneToggle/LabelMilestoneToggle.tsx
  client/src/components/molecules/Search/Search.tsx
  client/src/components/molecules/SelectMenuModal/SelectMenuModal.tsx
  client/src/components/molecules/TextWithIcon/TextWithIcon.tsx
  client/src/components/organisms/AppLayout/AppLayout.tsx
  client/src/components/organisms/IssueCard/IssueCard.stories.tsx
  client/src/components/organisms/IssueCard/IssueCard.tsx
  client/src/components/organisms/IssueListFilterHeader/IssueListFilterHeader.tsx
  client/src/components/organisms/IssueListFilterHeader/index.ts
  client/src/components/organisms/SearchWithFilter/SearchWithFilter.tsx
  client/src/components/organisms/SearchWithFilter/index.ts
  client/src/components/pages/Main/MainContainer.tsx
  client/src/components/pages/Main/MainPresenter.tsx
  client/src/hooks/useAsync.ts
  client/src/lib/axios.ts
  client/src/lib/convertType.ts
  client/src/stores/getIssues.ts
  client/src/stores/index.ts
  client/src/stores/type.ts
  client/src/themes/global.tsx
Labels: enhancement, refactor, view

#125 Jy/이슈 상세 화면 및 컴포넌트, 함수 구현
  client/src/apis/getIssue.ts
  client/src/app.tsx
  client/src/components/organisms/ContentWithProfile/ContentWithProfile.stories.tsx
  client/src/components/organisms/ContentWithProfile/ContentWithProfile.tsx
  client/src/components/organisms/ContentWithProfile/index.ts
  client/src/components/organisms/IssueContent/IssueContent.stories.tsx
  client/src/components/organisms/IssueContent/IssueContent.tsx
  client/src/components/organisms/IssueContent/index.ts
  client/src/components/pages/IssueDetail/IssueDetailContainer.tsx
  client/src/components/pages/IssueDetail/IssueDetailPresenter.tsx
  client/src/components/pages/IssueDetail/index.ts
  client/src/components/pages/Main/MainPresenter.tsx
  client/src/hooks/useDisplay.ts
  client/src/lib/convertType.ts
Labels: enhancement

#128 Feature/label,milestone select view
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Controller/Label/LabelAddViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Milestone/MilestoneAddViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Select/LabelCollectionViewSetting.swift
  iOS/IssueTracker/IssueTracker/Controller/Select/MilestoneCollectionViewSetting.swift
  iOS/IssueTracker/IssueTracker/Controller/Select/SelectViewController.swift
  iOS/IssueTracker/IssueTracker/Controller/Select/SelectViewController.xib
  iOS/IssueTracker/IssueTracker/Controller/Select/UserCollectionViewSetting.swift
  iOS/IssueTracker/IssueTracker/Extension/Extension.swift
  iOS/IssueTracker/IssueTracker/Model/DetailIssueDataManager.swift
  iOS/IssueTracker/IssueTracker/Model/MilestoneDataManager.swift
  iOS/IssueTracker/IssueTracker/Model/VO/DetailIssue.swift
  iOS/IssueTracker/IssueTracker/Model/VO/Labels.swift
  iOS/IssueTracker/IssueTracker/Model/VO/User.swift
  iOS/IssueTracker/IssueTracker/Storyboard/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/View/BottomDetailView.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/IssueDetailCollectionViewHeader.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/LabelCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/Select/SelectCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/Select/SelectCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/Select/SelectUserCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/View/CollectionViewCell/Select/SelectUserCollectionViewCell.xib
  iOS/IssueTracker/IssueTracker/View/Component/LabelView.swift
  iOS/IssueTracker/IssueTracker/View/InputView/ColorInputView.xib
Labels: enhancement, optional
